export enum Country {
  "AF" = "Afghanistan",
  "AL" = "Albania",
  "DZ" = "Algeria",
  "US" = "United States",
  "CA" = "Canada",
  "GB" = "United Kingdom",
  "DE" = "Germany",
  "FR" = "France",
  "JP" = "Japan",
  "CN" = "China",
  "IN" = "India",
  "AU" = "Australia",
  "BR" = "Brazil",
  "ZA" = "South Africa",
  "RU" = "Russia",
  "MX" = "Mexico",
  "IT" = "Italy",
  "ES" = "Spain",
  "KR" = "South Korea",
  "SA" = "Saudi Arabia"
}
