export const USER_LOCALSTORAGE_KEY = "SOCIAL_MEDIA_USER_LOCALSTORAGE_KEY";
export const ARTICLES_VIEW_LOCALSTORAGE_KEY = "SOCIAL_MEDIA_ARTICLES_VIEW_LOCALSTORAGE_KEY";
export const LOCAL_STORAGE_LAST_DESIGN_KEY = "";
