export const LOCAL_STORAGE_USER = "SOCIAL_MEDIA_USER";
export const LOCAL_STORAGE_ARTICLES_VIEW = "SOCIAL_MEDIA_ARTICLES_VIEW";
export const LOCAL_STORAGE_LAST_DESIGN_KEY = "SOCIAL_MEDIA_LAST_DESIGN";
export const LOCAL_STORAGE_THEME_KEY = "SOCIAL_MEDIA_THEME";
