name: Linting, Testing, Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install modules
        run: npm ci --force

      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting SCSS
        run: npm run lint:scss

  build-and-ui-testing:
    runs-on: ubuntu-latest
    needs: checks
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install modules
        run: npm ci --force

      - name: Build production project
        run: npm run build:prod

      - name: Build Storybook
        run: npm run storybook:build

      - name: Download Loki Reference Images
        uses: actions/download-artifact@v3
        with:
          name: loki-reference
          path: .loki/reference

      - name: Screenshot testing
        run: npm run test:ui:ci

      - name: Upload Loki Reference Images
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: loki-reference
          path: .loki/reference

      - name: Unit testing
        run: npm run test:unit

      - name: Generate HTML report
        run: npm run test:report:ui

      - name: Move Loki reports
        run: mkdir -p reports && mv .loki reports/

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-ui-testing
    steps:
      - name: Download Test Reports
        uses: actions/download-artifact@v3
        with:
          name: test-reports
          path: reports

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1